#
#  GNUmakefile for the PrintToFile test
#
#  Copyright (C) 2026 Daniel Boyd
#
#  This file is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public
#  License as published by the Free Software Foundation; either
#  version 2 of the License, or (at your option) any later version.
#

include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = PrintToFile
PrintToFile_OBJC_FILES = main.m
PrintToFile_TOOL_LIBS = -lgnustep-gui

include $(GNUSTEP_MAKEFILES)/tool.make
